service: uploadshare-backend
frameworkVersion: '3'

plugins:
  - serverless-plugin-log-retention
  - serverless-iam-roles-per-function

package:
  patterns:
    - "!test/**"

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  versionFunctions: false
  tracing:
    apiGateway: true
    lambda: true
  environment:
    BUCKET_NAME: !Ref FileBucket
    BASE_URL: https://${self:custom.domainName}
    POWERTOOLS_SERVICE_NAME: uploadshare
    POWERTOOLS_METRICS_NAMESPACE: uploadshare

custom:
  domainName: uploadshare.click
  logRetentionInDays: 7
  
functions:
  createShare:
    handler: handlers/share-handler.handle
    events:
      - httpApi:
          method: POST
          path: /
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource:
          - !Sub arn:aws:s3:::${FileBucket}/shares/*

  download:
    handler: handlers/download-handler.handle
    events:
      - httpApi:
          method: GET
          path: /{id}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource:
          - !Sub arn:aws:s3:::${FileBucket}/shares/*
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource:
          - !Sub arn:aws:s3:::${FileBucket}

resources:
  Resources:
    CustomDomainPathMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties:
        ApiId: !Ref HttpApi
        ApiMappingKey: 'share'
        DomainName: ${self:custom.domainName}
        Stage: !Ref HttpApiStage

    FileBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${file(./unique-bucket-name.cjs):bucketName}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        NotificationConfiguration:
          EventBridgeConfiguration:
            EventBridgeEnabled: true
