service: uploadshare-domain
frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-log-retention

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false

custom:
  logRetentionInDays: 7
  domainName: uploadshare.click

resources:
  Resources:
    PublicHostedZone:
      Type: AWS::Route53::HostedZone
      Properties:
        Name: ${self:custom.domainName}

    DomainCert:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: ${self:custom.domainName}
        ValidationMethod: DNS
        DomainValidationOptions:
          - DomainName: ${self:custom.domainName}
            HostedZoneId: !Ref PublicHostedZone

    ApiCustomDomain:
      Type: AWS::ApiGatewayV2::DomainName
      Properties:
        DomainName: ${self:custom.domainName}
        DomainNameConfigurations:
          - CertificateArn: !Ref DomainCert

    DomainRecordSet:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: !Ref PublicHostedZone
        RecordSets:
          - Name: ${self:custom.domainName}
            Type: A
            AliasTarget:
              DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
              HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId
          - Name: ${self:custom.domainName}
            Type: AAAA
            AliasTarget:
              DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
              HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId
